services:
  govt-travel-app:
    build: .
    container_name: govt-travel-estimator
    ports:
      - "5001:5001"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5001
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
